In [10]:
# Dependencies and set up
import pandas as pd
import numpy as np

In [11]:
# Reading csv
table = pd.read_csv('Resources/Crimes_-_2001_to_Present.csv')
table

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10224738,HY411648,09/05/2015 01:30:00 PM,043XX S WOOD ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,12.0,61.0,08B,1165074.0,1875917.0,2015,02/10/2018 03:50:01 PM,41.815117,-87.670000,"(41.815117282, -87.669999562)"
1,10224739,HY411615,09/04/2015 11:30:00 AM,008XX N CENTRAL AVE,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,...,29.0,25.0,06,1138875.0,1904869.0,2015,02/10/2018 03:50:01 PM,41.895080,-87.765400,"(41.895080471, -87.765400451)"
2,11646166,JC213529,09/01/2018 12:01:00 AM,082XX S INGLESIDE AVE,0810,THEFT,OVER $500,RESIDENCE,False,True,...,8.0,44.0,06,NaN,NaN,2018,04/06/2019 04:04:43 PM,NaN,NaN,NaN
3,10224740,HY411595,09/05/2015 12:45:00 PM,035XX W BARRY AVE,2023,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,...,35.0,21.0,18,1152037.0,1920384.0,2015,02/10/2018 03:50:01 PM,41.937406,-87.716650,"(41.937405765, -87.716649687)"
4,10224741,HY411610,09/05/2015 01:00:00 PM,0000X N LARAMIE AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,...,28.0,25.0,08A,1141706.0,1900086.0,2015,02/10/2018 03:50:01 PM,41.881903,-87.755121,"(41.881903443, -87.755121152)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7406831,12489699,JE382169,09/20/2021 08:30:00 PM,033XX E 91ST ST,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,True,...,10.0,46.0,26,1199886.0,1845255.0,2021,09/27/2021 04:51:51 PM,41.730171,-87.543339,"(41.730170665, -87.543339309)"
7406832,12489278,JE381903,09/20/2021 06:00:00 PM,030XX E 96TH ST,0560,ASSAULT,SIMPLE,RESIDENCE,False,True,...,10.0,51.0,08A,1198374.0,1841886.0,2021,09/27/2021 04:51:51 PM,41.720964,-87.548991,"(41.7209638, -87.548990551)"
7406833,12488842,JE381469,09/20/2021 10:00:00 PM,028XX E 81ST ST,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,True,...,7.0,46.0,14,1196325.0,1851803.0,2021,09/27/2021 04:51:51 PM,41.748228,-87.556167,"(41.74822785, -87.556167438)"
7406834,12488538,JE381166,09/20/2021 05:45:00 PM,061XX S ARCHER AVE,0860,THEFT,RETAIL THEFT,SMALL RETAIL STORE,True,False,...,23.0,56.0,06,1137711.0,1868195.0,2021,09/27/2021 04:51:51 PM,41.794463,-87.770558,"(41.794462581, -87.770558224)"
7406835,12488179,JE380617,09/20/2021 11:00:00 AM,045XX W MAYPOLE AVE,0560,ASSAULT,SIMPLE,RESIDENCE,False,False,...,28.0,26.0,08A,1145961.0,1901069.0,2021,09/27/2021 04:51:51 PM,41.884521,-87.739472,"(41.884521179, -87.739471702)"

In [12]:
# Primary type value counts
table.value_counts(subset=['Primary Type'])

Primary Type
THEFT                                1558259
BATTERY                              1358603
CRIMINAL DAMAGE                       844526
NARCOTICS                             739158
ASSAULT                               474492
OTHER OFFENSE                         460508
BURGLARY                              412187
MOTOR VEHICLE THEFT                   341406
DECEPTIVE PRACTICE                    317791
ROBBERY                               277935
CRIMINAL TRESPASS                     207594
WEAPONS VIOLATION                      92830
PROSTITUTION                           69443
OFFENSE INVOLVING CHILDREN             52105
PUBLIC PEACE VIOLATION                 51197
SEX OFFENSE                            28591
CRIM SEXUAL ASSAULT                    27840
INTERFERENCE WITH PUBLIC OFFICER       17725
GAMBLING                               14603
LIQUOR LAW VIOLATION                   14564
ARSON                                  12543
HOMICIDE                               11430
KIDNAPPING                              7044
INTIMIDATION                            4363
STALKING                                4088
CRIMINAL SEXUAL ASSAULT                 3812
CONCEALED CARRY LICENSE VIOLATION        804
OBSCENITY                                747
PUBLIC INDECENCY                         187
NON-CRIMINAL                             175
OTHER NARCOTIC VIOLATION                 140
HUMAN TRAFFICKING                         74
NON - CRIMINAL                            38
RITUALISM                                 24
NON-CRIMINAL (SUBJECT SPECIFIED)           9
DOMESTIC VIOLENCE                          1
dtype: int64

In [13]:
# Dropping NA
table.dropna(inplace=True)
table.shape

(6720206, 22)

In [14]:
# Replacing primary types
table.loc[table['Primary Type'] == 'OBSCENITY'] = 'OTHER'
table.loc[table['Primary Type'] == 'PUBLIC INDECENCY'] = 'OTHER'
table.loc[table['Primary Type'] == 'NON-CRIMINAL'] = 'OTHER'
table.loc[table['Primary Type'] == 'OTHER NARCOTIC VIOLATION'] = 'OTHER'
table.loc[table['Primary Type'] == 'HUMAN TRAFFICKING'] = 'OTHER'
table.loc[table['Primary Type'] == 'NON - CRIMINAL'] = 'OTHER'
table.loc[table['Primary Type'] == 'RITUALISM'] = 'OTHER'
table.loc[table['Primary Type'] == 'NON-CRIMINAL (SUBJECT SPECIFIED)'] = 'OTHER'
table.loc[table['Primary Type'] == 'DOMESTIC VIOLENCE'] = 'OTHER'
table.loc[table['Primary Type'] == 'CONCEALED CARRY LICENSE VIOLATION'] = 'OTHER'

In [15]:
# Primary type value counts
table.value_counts(subset=['Primary Type'])

Primary Type
THEFT                               1418131
BATTERY                             1235950
CRIMINAL DAMAGE                      769659
NARCOTICS                            662554
ASSAULT                              433196
OTHER OFFENSE                        417811
BURGLARY                             378345
MOTOR VEHICLE THEFT                  305851
DECEPTIVE PRACTICE                   280759
ROBBERY                              253637
CRIMINAL TRESPASS                    189321
WEAPONS VIOLATION                     86900
PROSTITUTION                          60952
PUBLIC PEACE VIOLATION                47589
OFFENSE INVOLVING CHILDREN            46475
SEX OFFENSE                           24497
CRIM SEXUAL ASSAULT                   24321
INTERFERENCE WITH PUBLIC OFFICER      17156
GAMBLING                              13390
LIQUOR LAW VIOLATION                  12450
ARSON                                 11166
HOMICIDE                              11047
KIDNAPPING                             5842
INTIMIDATION                           3970
STALKING                               3768
CRIMINAL SEXUAL ASSAULT                3380
OTHER                                  2089
dtype: int64

In [16]:
# Columns
list(table.columns)

['ID',
 'Case Number',
 'Date',
 'Block',
 'IUCR',
 'Primary Type',
 'Description',
 'Location Description',
 'Arrest',
 'Domestic',
 'Beat',
 'District',
 'Ward',
 'Community Area',
 'FBI Code',
 'X Coordinate',
 'Y Coordinate',
 'Year',
 'Updated On',
 'Latitude',
 'Longitude',
 'Location']

In [17]:
# Dropping columns
table.drop(['ID', 'Case Number', 'Block', 'IUCR', 'Beat', 'District', 'Community Area', 'FBI Code','Updated On', 'Location'], axis = 1, inplace = True)
list(table.columns)

['Date',
 'Primary Type',
 'Description',
 'Location Description',
 'Arrest',
 'Domestic',
 'Ward',
 'X Coordinate',
 'Y Coordinate',
 'Year',
 'Latitude',
 'Longitude']

In [18]:
table.drop(['X Coordinate', 'Y Coordinate'], axis = 1, inplace = True)
list(table.columns)

['Date',
 'Primary Type',
 'Description',
 'Location Description',
 'Arrest',
 'Domestic',
 'Ward',
 'Year',
 'Latitude',
 'Longitude']

In [19]:
df = table.drop_duplicates(subset = 'Location Description', keep = 'first')
df = df['Location Description']
df

0                                  RESIDENCE
1                                    CTA BUS
3                                   SIDEWALK
4                                  APARTMENT
6                           RESIDENCE-GARAGE
                         ...
3225103                         BANQUET HALL
5349596                         LOADING DOCK
6823433                   CTA SUBWAY STATION
6888299                    BOAT / WATERCRAFT
7033250    VEHICLE - COMMERCIAL: TROLLEY BUS
Name: Location Description, Length: 214, dtype: object

In [20]:
df.to_csv(r'Resources/Location Description.csv', index = False)

In [22]:
table.loc[table['Location Description'] == 'AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA'] = 'AIRPORT'
table.loc[table['Location Description'] == 'AIRPORT BUILDING NON-TERMINAL - SECURE AREA'] = 'AIRPORT'
table.loc[table['Location Description'] == 'AIRPORT EXTERIOR - NON-SECURE AREA'] = 'AIRPORT'
table.loc[table['Location Description'] == 'AIRPORT EXTERIOR - SECURE AREA'] = 'AIRPORT'
table.loc[table['Location Description'] == 'AIRPORT TERMINAL LOWER LEVEL - NON-SECURE AREA'] = 'AIRPORT'
table.loc[table['Location Description'] == 'AIRPORT TERMINAL LOWER LEVEL - SECURE AREA'] = 'AIRPORT'
table.loc[table['Location Description'] == 'AIRPORT TERMINAL MEZZANINE - NON-SECURE AREA'] = 'AIRPORT'
table.loc[table['Location Description'] == 'AIRPORT TERMINAL UPPER LEVEL - NON-SECURE AREA'] = 'AIRPORT'
table.loc[table['Location Description'] == 'AIRPORT TERMINAL UPPER LEVEL - SECURE AREA'] = 'AIRPORT'
table.loc[table['Location Description'] == 'AIRPORT TRANSPORTATION SYSTEM (ATS)'] = 'AIRPORT'
table.loc[table['Location Description'] == 'AIRPORT VENDING ESTABLISHMENT'] = 'AIRPORT'
table.loc[table['Location Description'] == 'AIRPORT/AIRCRAFT'] = 'AIRPORT'
table.loc[table['Location Description'] == 'AIRCRAFT'] = 'AIRPORT'

In [23]:
table.loc[table['Location Description'] == 'CHURCH'] = 'CHURCH'
table.loc[table['Location Description'] == 'CHURCH / SYNAGOGUE / PLACE OF WORSHIP'] = 'CHURCH'
table.loc[table['Location Description'] == 'CHURCH PROPERTY'] = 'CHURCH'
table.loc[table['Location Description'] == 'CHURCH/SYNAGOGUE/PLACE OF WORSHIP'] = 'CHURCH'

In [24]:
table.loc[table['Location Description'] == 'APPLIANCE STORE'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'ATHLETIC CLUB'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'BANK'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'BANQUET HALL'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'BARBER SHOP/BEAUTY SALON'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'BARBERSHOP'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'BOWLING ALLEY'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'CLEANERS/LAUNDROMAT'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'CLEANING STORE'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'CLUB'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'COIN OPERATED MACHINE'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'COMMERCIAL / BUSINESS OFFICE'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'CONVENIENCE STORE'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'CREDIT UNION'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'CURRENCY EXCHANGE'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'DEPARTMENT STORE'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'DRUG STORE'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'FACTORY'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'FACTORY / MANUFACTURING BUILDING'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'FACTORY/MANUFACTURING BUILDING'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'FARM'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'FUNERAL PARLOR'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'GARAGE/AUTO REPAIR'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'GAS STATION'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'GAS STATION DRIVE/PROP.'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'GROCERY FOOD STORE'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'HALLWAY'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'HORSE STABLE'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'KENNEL'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'LAUNDRY ROOM'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'LIQUOR STORE'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'MOTEL'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'OFFICE'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'PAWN SHOP'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'RESTAURANT'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'RETAIL STORE'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'SAVINGS AND LOAN'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'SMALL RETAIL STORE'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'TRUCKING TERMINAL'] = 'COMMERCIAL BUILDING'
table.loc[table['Location Description'] == 'WAREHOUSE'] = 'COMMERCIAL BUILDING'

In [27]:
table.loc[table['Location Description'] == 'CTA "L" PLATFORM'] = 'CTA'
table.loc[table['Location Description'] == 'CTA "L" TRAIN'] = 'CTA'
table.loc[table['Location Description'] == 'CTA BUS'] = 'CTA'
table.loc[table['Location Description'] == 'CTA BUS STOP'] = 'CTA'
table.loc[table['Location Description'] == 'CTA GARAGE / OTHER PROPERTY'] = 'CTA'
table.loc[table['Location Description'] == 'CTA PLATFORM'] = 'CTA'
table.loc[table['Location Description'] == 'CTA PROPERTY'] = 'CTA'
table.loc[table['Location Description'] == 'CTA STATION'] = 'CTA'
table.loc[table['Location Description'] == 'CTA SUBWAY STATION'] = 'CTA'
table.loc[table['Location Description'] == 'CTA TRACKS - RIGHT OF WAY'] = 'CTA'
table.loc[table['Location Description'] == 'CTA TRAIN'] = 'CTA'
table.loc[table['Location Description'] == 'CTA PARKING LOT / GARAGE / OTHER PROPERTY'] = 'CTA'

In [28]:
table.loc[table['Location Description'] == 'COLLEGE / UNIVERSITY - GROUNDS'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'COLLEGE / UNIVERSITY - RESIDENCE HALL'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'COLLEGE/UNIVERSITY GROUNDS'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'COLLEGE/UNIVERSITY RESIDENCE HALL'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'DAY CARE CENTER'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'PUBLIC GRAMMAR SCHOOL'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'PUBLIC HIGH SCHOOL'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'SCHOOL - PRIVATE BUILDING'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'SCHOOL - PRIVATE GROUNDS'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'SCHOOL - PUBLIC BUILDING'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'SCHOOL - PUBLIC GROUNDS'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'SCHOOL YARD'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'SCHOOL, PRIVATE, BUILDING'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'SCHOOL, PRIVATE, GROUNDS'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'SCHOOL, PUBLIC, BUILDING'] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == 'SCHOOL, PUBLIC, GROUNDS'] = 'EDUCATIONAL BUILDING'

In [ ]:
table.loc[table['Location Description'] == ' '] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == ' '] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == ' '] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == ' '] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == ' '] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == ' '] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == ' '] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == ' '] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == ' '] = 'EDUCATIONAL BUILDING'
table.loc[table['Location Description'] == ' '] = 'EDUCATIONAL BUILDING'