In [2]:
# Dependencies and set up
import pandas as pd
import numpy as np

In [3]:
# Reading csv
table = pd.read_csv('Resources/Crimes_-_2001_to_Present.csv')
table

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10224738,HY411648,09/05/2015 01:30:00 PM,043XX S WOOD ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,12.0,61.0,08B,1165074.0,1875917.0,2015,02/10/2018 03:50:01 PM,41.815117,-87.670000,"(41.815117282, -87.669999562)"
1,10224739,HY411615,09/04/2015 11:30:00 AM,008XX N CENTRAL AVE,0870,THEFT,POCKET-PICKING,CTA BUS,False,False,...,29.0,25.0,06,1138875.0,1904869.0,2015,02/10/2018 03:50:01 PM,41.895080,-87.765400,"(41.895080471, -87.765400451)"
2,11646166,JC213529,09/01/2018 12:01:00 AM,082XX S INGLESIDE AVE,0810,THEFT,OVER $500,RESIDENCE,False,True,...,8.0,44.0,06,NaN,NaN,2018,04/06/2019 04:04:43 PM,NaN,NaN,NaN
3,10224740,HY411595,09/05/2015 12:45:00 PM,035XX W BARRY AVE,2023,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,...,35.0,21.0,18,1152037.0,1920384.0,2015,02/10/2018 03:50:01 PM,41.937406,-87.716650,"(41.937405765, -87.716649687)"
4,10224741,HY411610,09/05/2015 01:00:00 PM,0000X N LARAMIE AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,...,28.0,25.0,08A,1141706.0,1900086.0,2015,02/10/2018 03:50:01 PM,41.881903,-87.755121,"(41.881903443, -87.755121152)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7406205,12487794,JE380159,09/19/2021 11:52:00 PM,064XX S MOZART ST,041A,BATTERY,AGGRAVATED - HANDGUN,SIDEWALK,False,False,...,17.0,66.0,04B,1158484.0,1861911.0,2021,09/26/2021 04:48:34 PM,41.776820,-87.694555,"(41.776819976, -87.694554571)"
7406206,12487637,JE379677,09/19/2021 02:30:00 PM,018XX W CULLERTON ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,25.0,31.0,08B,1164319.0,1890435.0,2021,09/26/2021 04:48:34 PM,41.854972,-87.672359,"(41.854972152, -87.672359238)"
7406207,12494028,JE387722,09/14/2021 01:00:00 PM,020XX E 83RD ST,0610,BURGLARY,FORCIBLE ENTRY,RESIDENCE - GARAGE,False,False,...,8.0,46.0,05,NaN,NaN,2021,09/26/2021 04:48:34 PM,NaN,NaN,NaN
7406208,12487336,JE379561,09/19/2021 12:30:00 AM,119XX S CALUMET AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,9.0,53.0,14,1180370.0,1825895.0,2021,09/26/2021 04:48:34 PM,41.677514,-87.615423,"(41.677513514, -87.615422762)"
7406209,12487014,JE379294,09/19/2021 08:20:00 AM,001XX E 49TH ST,1477,WEAPONS VIOLATION,RECKLESS FIREARM DISCHARGE,ALLEY,False,False,...,3.0,38.0,15,1178150.0,1872573.0,2021,09/26/2021 04:48:34 PM,41.805654,-87.622137,"(41.805654056, -87.622136589)"

In [4]:
# Primary type value counts
table.value_counts(subset=['Primary Type'])

Primary Type
THEFT                                1558131
BATTERY                              1358490
CRIMINAL DAMAGE                       844453
NARCOTICS                             739154
ASSAULT                               474426
OTHER OFFENSE                         460461
BURGLARY                              412164
MOTOR VEHICLE THEFT                   341368
DECEPTIVE PRACTICE                    317753
ROBBERY                               277897
CRIMINAL TRESPASS                     207584
WEAPONS VIOLATION                      92805
PROSTITUTION                           69443
OFFENSE INVOLVING CHILDREN             52098
PUBLIC PEACE VIOLATION                 51194
SEX OFFENSE                            28587
CRIM SEXUAL ASSAULT                    27841
INTERFERENCE WITH PUBLIC OFFICER       17725
GAMBLING                               14603
LIQUOR LAW VIOLATION                   14564
ARSON                                  12542
HOMICIDE                               11428
KIDNAPPING                              7043
INTIMIDATION                            4362
STALKING                                4087
CRIMINAL SEXUAL ASSAULT                 3810
CONCEALED CARRY LICENSE VIOLATION        803
OBSCENITY                                746
PUBLIC INDECENCY                         187
NON-CRIMINAL                             175
OTHER NARCOTIC VIOLATION                 140
HUMAN TRAFFICKING                         74
NON - CRIMINAL                            38
RITUALISM                                 24
NON-CRIMINAL (SUBJECT SPECIFIED)           9
DOMESTIC VIOLENCE                          1
dtype: int64

In [5]:
# Dropping NA
table.dropna(inplace=True)
table.shape

(6719641, 22)

In [6]:
# Replacing primary types
table.loc[table['Primary Type'] == 'OBSCENITY'] = 'OTHER'
table.loc[table['Primary Type'] == 'PUBLIC INDECENCY'] = 'OTHER'
table.loc[table['Primary Type'] == 'NON-CRIMINAL'] = 'OTHER'
table.loc[table['Primary Type'] == 'OTHER NARCOTIC VIOLATION'] = 'OTHER'
table.loc[table['Primary Type'] == 'HUMAN TRAFFICKING'] = 'OTHER'
table.loc[table['Primary Type'] == 'NON - CRIMINAL'] = 'OTHER'
table.loc[table['Primary Type'] == 'RITUALISM'] = 'OTHER'
table.loc[table['Primary Type'] == 'NON-CRIMINAL (SUBJECT SPECIFIED)'] = 'OTHER'
table.loc[table['Primary Type'] == 'DOMESTIC VIOLENCE'] = 'OTHER'
table.loc[table['Primary Type'] == 'CONCEALED CARRY LICENSE VIOLATION'] = 'OTHER'

In [7]:
# Primary type value counts
table.value_counts(subset=['Primary Type'])

Primary Type
THEFT                               1418020
BATTERY                             1235838
CRIMINAL DAMAGE                      769589
NARCOTICS                            662550
ASSAULT                              433133
OTHER OFFENSE                        417774
BURGLARY                             378325
MOTOR VEHICLE THEFT                  305815
DECEPTIVE PRACTICE                   280739
ROBBERY                              253601
CRIMINAL TRESPASS                    189311
WEAPONS VIOLATION                     86875
PROSTITUTION                          60952
PUBLIC PEACE VIOLATION                47586
OFFENSE INVOLVING CHILDREN            46470
SEX OFFENSE                           24494
CRIM SEXUAL ASSAULT                   24322
INTERFERENCE WITH PUBLIC OFFICER      17156
GAMBLING                              13390
LIQUOR LAW VIOLATION                  12450
ARSON                                 11165
HOMICIDE                              11044
KIDNAPPING                             5841
INTIMIDATION                           3969
STALKING                               3767
CRIMINAL SEXUAL ASSAULT                3378
OTHER                                  2087
dtype: int64

In [8]:
# Columns
list(table.columns)

['ID',
 'Case Number',
 'Date',
 'Block',
 'IUCR',
 'Primary Type',
 'Description',
 'Location Description',
 'Arrest',
 'Domestic',
 'Beat',
 'District',
 'Ward',
 'Community Area',
 'FBI Code',
 'X Coordinate',
 'Y Coordinate',
 'Year',
 'Updated On',
 'Latitude',
 'Longitude',
 'Location']

In [9]:
# Dropping columns
table.drop(['ID', 'Case Number', 'Updated On', 'Location', 'Ward', 'Community Area', 'Beat'], axis = 1, inplace = True)
list(table.columns)

['Date',
 'Block',
 'IUCR',
 'Primary Type',
 'Description',
 'Location Description',
 'Arrest',
 'Domestic',
 'District',
 'FBI Code',
 'X Coordinate',
 'Y Coordinate',
 'Year',
 'Latitude',
 'Longitude']

In [13]:
# Primary type value counts
lc_table = table['Location Description']
lc_table

0          RESIDENCE
1            CTA BUS
3           SIDEWALK
4          APARTMENT
5          RESIDENCE
             ...
7406204    RESIDENCE
7406205     SIDEWALK
7406206    APARTMENT
7406208       STREET
7406209        ALLEY
Name: Location Description, Length: 6719641, dtype: object