In [27]:
# Dependencies and Setup
import requests
import time
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy.stats as st
from scipy.stats import linregress
from pprint import pprint

# In case you change unix timestamp
from datetime import datetime
from pytz import timezone

# Looking up for city names with geo-coordinates 
from citipy import citipy

# API keys
# from api_keys import w_key
# from api_keys import g_key

# Range of Latitude and Longitude
lat_r = (41.64, 42.03)
lng_r = (-87.90, -87.53)

In [30]:
# Empty list for Latitude and Longitude and cities
lat_lng = []
c_list = []

# Random set of Latitude and Longitude / size number must be modify according to confirmed cities
lat = np.random.uniform(lat_r[0], lat_r[1], size = 2000)
lng = np.random.uniform(lng_r[0], lng_r[1], size = 2000)
lat_lng = zip(lat,lng)

# Using Citipy for looking the nearest city using lat_lng
for lat_lng in lat_lng:
    c = citipy.nearest_city(lat_lng[0],lat_lng[1]).city_name
    
    # Conditional for identifying unique city and append for adding in c_list 
    if c not in c_list:
            c_list.append(c)

# Number of cities in c_list to be confirmed
len(c_list)

48

In [31]:
# Cities DataFrame
city_data = pd.DataFrame({'City': c_list})
city_data

               City
0       lincolnwood
1           chicago
2     chicago ridge
3            dolton
4          evanston
5    evergreen park
6         crestwood
7            cicero
8     schiller park
9       blue island
10          maywood
11     elmwood park
12      orland park
13         bellwood
14    hickory hills
15         oak park
16      river grove
17         norridge
18       bridgeview
19      des plaines
20        la grange
21      palos hills
22       brookfield
23            worth
24           summit
25    franklin park
26      westchester
27         oak lawn
28     calumet city
29   goodings grove
30   la grange park
31            lyons
32     melrose park
33          burbank
34      forest park
35            niles
36    palos heights
37           berwyn
38       park ridge
39        northlake
40  western springs
41          justice
42        riverdale
43     morton grove
44     river forest
45       burr ridge
46            alsip
47           skokie